name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    uses: bloock/actions/.github/workflows/build.yml@master
    with:
      image: enchainteregistry.azurecr.io/enchainte/valid-proof
