name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    uses: bloock/actions/.github/workflows/build.yml@master
    with:
      image: enchainteregistry.azurecr.io/enchainte/valid-proof
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy-dev:
    name: Deploy to development
    uses: bloock/actions/.github/workflows/deployer.yml@master
    if: github.ref == 'refs/heads/master'
    with:
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof:${{ inputs.tag }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}
  deploy-pro:
    name: Deploy to production
    uses: bloock/actions/.github/workflows/deployer.yml@master
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    with:
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof:${{ inputs.tag }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PRO }}
