name: deploy-dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: true

jobs:
  deploy:
    name: Deploy to development
    uses: bloock/actions/.github/workflows/deployer.yml@master
    with:
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof
      tag: ${{ inputs.tag }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}