name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - "development"
          - "production"
        required: true
      tag:
        description: "Image Tag"
        required: true
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true
      tag:
        description: "Image Tag"
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    uses: bloock/actions/.github/workflows/deployer.yml@master
    with:
      environment: ${{ inputs.environment }}
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof:${{ inputs.tag }}
