name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - "development"
          - "production"
        required: true
      tag:
        description: "Image Tag"
        required: true

jobs:
  deploy-dev:
    name: Deploy to development
    uses: bloock/actions/.github/workflows/deployer.yml@master
    if: ${{ inputs.environment }} == "development"
    with:
      environment: ${{ inputs.environment }}
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof:${{ inputs.tag }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}
  deploy-pro:
    name: Deploy to production
    uses: bloock/actions/.github/workflows/deployer.yml@master
    if: ${{ inputs.environment }} == "production"
    with:
      environment: ${{ inputs.environment }}
      service: valid-proof
      container: valid-proof
      image: enchainte/valid-proof:${{ inputs.tag }}
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PRO }}
